### PR TITLE
not to use Partial class for null object

### PR DESCRIPTION
**Pull request by Summer498**
The difference in type between Note and NoNote is annoying when using the library. Thus, the type of null object was changed to the same type as the original object, like Note, instead of the Parital type like NoNote.

### CODE REVIEW

**Comment by Summer498** [comment]
I wondef if my word "annoying" is offensible. This word is from my low skill of English...

**Comment by danigb** [comment]
Hi, thanks for the contribution. However, not sure if it's so easy: I don't agree a "NoInterval" has 0 semitones. For me that's a perfect 1st and I want to be able to distinguish. So, maybe we need to rethink a little bit: what is exactly the problem you want to solve? Maybe that helps me to understand or find a solution... 

I'm not a native English speaker neither, so I don't know if annoying is offensive 😂

**Comment by Summer498** [comment]
Hi,

Thanks for your reply 😀!



> I want to be able to distinguish it.



I figured I could use the value of .empty being true to distinguish and set the values of the other members as dummies.





> what is exactly the problem you want to solve?



In my program I intend to enter the correct interval string in the argument of `Interval.get`. And I want to use the type returned from the get method in my program as `type TInterval = RetrunValue<Interval.get>;`.

  - To say more honestly, I wanted tonal to throw error if parse failed.

    - I thought that throwing an error would be a major change, so I figured to change it not to use types such as `NoInterval` for now.



Here, `RetrunValue<Interval.get>` is `Interval | NoInterval`, which means that even though I know that only `Interval` will be returned (because we are inputting the correct interval string), I have to consider about `NoInterval`.

**Comment by danigb** [comment]
> To say more honestly, I wanted tonal to throw error if parse failed.
Okey, yes. That was an old design decision not easy to solve... unless you wrap the code with your own get interval:

```ts
function getInterval(value: string): Interval {
  const interval = Interval.get(interval);
  if (interval.empty) throw Error("Invalid interval");
  return interval;
}
```

Does it work? Or said in another way: why you can't test `interval.empty` yourself?

Maybe if you post some code, we can dive deeper into the issue

**Comment by Summer498** [comment]
Hi, 😉

> why you can't test interval.empty yourself?

The reason I have not tested `.empty` myself is simply for the sake of code cleanliness. I am not actually experiencing any bugs or other problems.
- But, I can look up `if(interval.empty)` in my own program or write a wrapper to make it work without any particular problems.
- Actually, I had previously created a wrapper like the one you described to deal with this (and it worked fine), but I decided to send a PR because I thought it would be cleaner to fix the library side of the code.
  - The reason for sending the PR is not just because it makes my own code cleaner, but because I thought that simplifying the return type of the function would be desirable for the behavior of the library.

Simply say, I am just proposing a change of type based on my thoughts.
  - I wonder if it would have been better to send the propose for Issue instead of a PR. 🤔

By the way, I am referring to the idea below: 😘
- [Robustness_principle](https://en.wikipedia.org/wiki/Robustness_principle)
  - Wikipedia emphasizes generosity with respect to inputs, but I am referring more to the idea that it should be simpler/limited/fewer-options with respect to outputs.

**Comment by danigb** [comment]
So, let me see if I understood: the problem is not the usage of a null object (something that, right now, I'm not sure if it was a good idea...). The actual problem is that we use two different types for the output, and that implies you need to check the "empty" (discriminatory) field before accessing a data field... 🤔 

And the proposed solution is that "empty" (aka null object) contains all the fields but with "dummy" values... As a side note, I guess that's a breaking change...

🤔  Okey, maybe it is a good idea, but not 100% sure... I don't like the fact that "empty" objects has some values different from undefined, but I'm sure that I don't want to make fields optional...

**Comment by Summer498** [comment]
> So, let me see if I understood: the problem is not the usage of a null object (something that, right now, I'm not sure if it was a good idea...). The actual problem is that we use two different types for the output, and that implies you need to check the "empty" (discriminatory) field before accessing a data field... 🤔

To be honest, I have thought the useage of null objects is also a problem. But I stopped sending PR because I thought it would be a breaking change.
And I thought the change to stop using two different types was not so breaking, so I sent a PR. But it seems to be more breaking than I thought. (Thank you for making me realize.😉)

The change was more breaking than I expected. So I'm starting to think about withdrawing the request and close PR. I don't want to bother you any more. 🙇‍♀️
- It is able to say that the issue occurring within my program is a issue of my preference, so I will personally solve it within my program (e.g. like you told, make wrapper function).

**Comment by danigb** [comment]
I've finally decided to implement your suggestion. Thanks for bringing that up

**Pull request closed without merging**
