### PR TITLE
fix: stringify cache keys across packages

### LINKED ISSUE #347: memory leak in note function
Hey! I noticed that when doing a lot of note operations over a longer period of time, the browser heap memory grows and grows. After digging through heap snapshots, I found the note cache littered with objects. Because [strudel](https://strudel.tidalcycles.org/) makes heavy use of this lib, the heap happens to creep to over 100MB in a matter of minutes, compared to ~10MB without using tonal functions.

Example of a problematic call stack:

`Note.transpose("A", "3m")` -> `coordToNote([0])` -> `note({step: 0, alt: 0, dir: undefined })`

The cache inside the `note` function works like this:

```js
const cache = new Map();

/* .. */
function note(src) {
    const cached = cache.get(src);
    if (cached) {
        return cached;
    }
    const value = /* .. */
    cache.set(src, value);
    return value;
}
```

Now the problem is that `cache.get({ /* .. */ })` will always be undefined. Try running this in the browser console:

```js
const cache = new Map();
cache.set({ foo: true }, 'hello');
cache.get({ foo: true}); // undefined
```

The memory leak happens with `cache.set(src, value);`, making sure the object stays in memory until forever.

An easy fix would be to skip the cache logic when `src` is an object.

### PR DESCRIPTION
**Pull request by manniL**
This PR includes commits to stringify map keys for caching ☺️ 
Please rebase and do not squash 😋

Resolves #347 

cc @felixroos - feel free to check

### CODE REVIEW

**Comment by felixroos** [comment]
that fixes it! thank you

**Comment by danigb** [comment]
Hi @manniL thanks for the PR. In this library, I prefer squash to have one commit per issue. Why do you prefer rebase?

**Comment by manniL** [comment]
@danigb Usually I prefer squash too but because those commits could've been two distinct PRs, I'd go for rebase this one time to preserve both commits. 😋

**Comment by danigb** [comment]
If you don't mind, since this is an implementation detail (there are no tests nor documentation) I don't consider two different issues, so I'd prefer to squash.

**Comment by manniL** [comment]
Yes sure 👍🏻

**Pull request merged**
