### PR TITLE
Add fretty.app to the list of projects using tonal

### PR DESCRIPTION
**Pull request by tfeldmann**
Site: https://fretty.app

And thanks a lot for this lib 👍

### CODE REVIEW

**Comment by dev6rodn** [comment]
@tfeldmann, any plans to open source your project? I had a peek and it's pretty neat!

**Comment by tfeldmann** [comment]
Thank you and yes, I'm going to open source it in the future.

**Comment by danigb** [comment]
Very cool! Thanks!

**Comment by tfeldmann** [comment]
> @tfeldmann, any plans to open source your project? I had a peek and it's pretty neat!

It's open source now 👍

**Pull request merged**
